CREATE TRIGGER unique_app_name
AFTER INSERT OR UPDATE ON app
FOR EACH ROW EXECUTE PROCEDURE check_unique();

CREATE OR REPLACE FUNCTION check_unique() RETURNS trigger AS
$$
	BEGIN
		IF NEW.app_name IS NULL THEN 
 			RAISE EXCEPTION  'APP NAME CAN NOT BE EMPTY';
		END IF;
		RETURN NULL;
	END;
$$ 
LANGUAGE 'plpgsql';


